
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programAND ID LPAREN NEG OR RPAREN\n        program : query\n        \n        query : atom logic query\n        \n        query : LPAREN query RPAREN\n        \n        query : atom\n        \n        atom : term\n        \n        atom : NEG term\n        \n        term : ID\n        \n        logic : AND\n              | OR\n        '
    
_lr_action_items = {'LPAREN':([0,4,8,9,10,],[4,4,4,-8,-9,]),'NEG':([0,4,8,9,10,],[6,6,6,-8,-9,]),'ID':([0,4,6,8,9,10,],[7,7,7,7,-8,-9,]),'$end':([1,2,3,5,7,12,13,14,],[0,-1,-4,-5,-7,-6,-2,-3,]),'RPAREN':([3,5,7,11,12,13,14,],[-4,-5,-7,14,-6,-2,-3,]),'AND':([3,5,7,12,],[9,-5,-7,-6,]),'OR':([3,5,7,12,],[10,-5,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'query':([0,4,8,],[2,11,13,]),'atom':([0,4,8,],[3,3,3,]),'term':([0,4,6,8,],[5,5,12,5,]),'logic':([3,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> query','program',1,'p_program','parse_query.py',17),
  ('query -> atom logic query','query',3,'p_query','parse_query.py',23),
  ('query -> LPAREN query RPAREN','query',3,'p_query_paren','parse_query.py',29),
  ('query -> atom','query',1,'p_query_atom','parse_query.py',35),
  ('atom -> term','atom',1,'p_atom_simple','parse_query.py',41),
  ('atom -> NEG term','atom',2,'p_atom_neg','parse_query.py',47),
  ('term -> ID','term',1,'p_term','parse_query.py',53),
  ('logic -> AND','logic',1,'p_logic','parse_query.py',60),
  ('logic -> OR','logic',1,'p_logic','parse_query.py',61),
]
